name: Convert YAML to JSON

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install pyyaml

    - name: Convert YAML to JSON
      run: |
        python -c "import yaml, json; json.dump(yaml.safe_load(open('path/to/yaml/file.yml')), open('path/to/json/file.json', 'w'), indent=4)"
